//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Validators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApi.Validators.ValidationErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email should not be empty!.
        /// </summary>
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id should not be empty!.
        /// </summary>
        public static string EmptyId {
            get {
                return ResourceManager.GetString("EmptyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location should not be empty!.
        /// </summary>
        public static string EmptyLocation {
            get {
                return ResourceManager.GetString("EmptyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not be empty!.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type should not be empty!.
        /// </summary>
        public static string EmptyType {
            get {
                return ResourceManager.GetString("EmptyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should not be empty!.
        /// </summary>
        public static string EmptyUsername {
            get {
                return ResourceManager.GetString("EmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id doesn&apos;t exist..
        /// </summary>
        public static string InexistentId {
            get {
                return ResourceManager.GetString("InexistentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address isn&apos;t registered..
        /// </summary>
        public static string InexistentLoginEmail {
            get {
                return ResourceManager.GetString("InexistentLoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability should be Available, Away.
        /// </summary>
        public static string InvalidAvailability {
            get {
                return ResourceManager.GetString("InvalidAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid!.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Length should have 24 characters!.
        /// </summary>
        public static string InvalidIdLength {
            get {
                return ResourceManager.GetString("InvalidIdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id doesn&apos;t respect the ObjectId structure..
        /// </summary>
        public static string InvalidIdStructure {
            get {
                return ResourceManager.GetString("InvalidIdStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tickets should be greater than 0!.
        /// </summary>
        public static string InvalidNumberOfTickets {
            get {
                return ResourceManager.GetString("InvalidNumberOfTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill should be Software, Hardware, Hr.
        /// </summary>
        public static string InvalidSkill {
            get {
                return ResourceManager.GetString("InvalidSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type should be Client, Employee or CallCenter.
        /// </summary>
        public static string InvalidUserType {
            get {
                return ResourceManager.GetString("InvalidUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should have at least 1 digit!.
        /// </summary>
        public static string NoDigitPassword {
            get {
                return ResourceManager.GetString("NoDigitPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email already taken! Try another email!.
        /// </summary>
        public static string NotUniqueEmail {
            get {
                return ResourceManager.GetString("NotUniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location should have minimum 1 character!.
        /// </summary>
        public static string ShortLocation {
            get {
                return ResourceManager.GetString("ShortLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should have minimum 4 characters!.
        /// </summary>
        public static string ShortPassword {
            get {
                return ResourceManager.GetString("ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should have between 2 and 25 characters!.
        /// </summary>
        public static string ShortUsername {
            get {
                return ResourceManager.GetString("ShortUsername", resourceCulture);
            }
        }
    }
}
